version: 2.1

commands:
  abort_for_docs:
    steps:
      - run:
          name: Avoid tests for docs
          command: |
            if [[ $CIRCLE_BRANCH == *_docs ]]; then
              echo "Identifies as documents PR, no testing required"
              circleci step halt
            fi

  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

  setup-executor:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - setup_remote_docker:
          docker_layer_caching: true

  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            git submodule update --init deps/readies
            ./deps/readies/bin/getpy3

  checkout-all:
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive

  persist-artifacts:
    steps:
      - persist_to_workspace:
          root: bin/
          paths:
            - artifacts/snapshots/*.zip
            - artifacts/snapshots/*.tgz
            - artifacts/snapshots/*.tar
            - artifacts/*.zip
            - artifacts/*.tgz
            - artifacts/*.tar
      - run:
          name: Cleanup test log dir
          command: rm -f tests/flow/logs/*.rdb
      - store_artifacts:
          path: tests/flow/logs
  
  build_steps:
    parameters:
      platform:
        type: string
      getredis_params:
        type: string
        default: ""
      build_params:
        type: string
        default: ""
      test_params:
        type: string
        default: ""
    steps:
      - abort_for_docs
      - checkout-all
      - setup-automation
      - run:
          name: Install prerequisites
          command: make setup
      - run:
          name: Install Redis
          command: |
            python3 ./deps/readies/bin/getredis -v 6 --force <<parameters.getredis_params>>
            redis-server --version
      - run:
          name: Build
          command: make build <<parameters.build_params>> SHOW=1
      - run:
          name: Pack
          command: make pack SHOW=1
      - run:
          name: Unit Test
          command: |
            mkdir -p ~/workspace/tests
            make unittests TEST_REPORT_DIR=$HOME/workspace/tests <<parameters.test_params>> SHOW=1
      - run:
          name: Flow Test
          no_output_timeout: 30m
          command: |
            mkdir -p ~/workspace/tests
            make test TEST_REPORT_DIR=$HOME/workspace/tests <<parameters.test_params>> SHOW=1

  platforms-build-steps:
    parameters:
      platform:
        type: string
    steps:
      - abort_for_docs
      - setup-executor
      - checkout-all
      - setup-automation
      - run:
          name: Build for platform
          command: |
            cd build/docker
            make build OSNICK=<<parameters.platform>> VERSION=$CIRCLE_TAG BRANCH=$CIRCLE_BRANCH ARTIFACTS=1 TEST=1 SHOW=1
          no_output_timeout: 30m
      - early_return_for_forked_pull_requests
      - run:
          name: Build for platform (publish)
          command: |
            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            cd build/docker
            make publish OSNICK=<<parameters.platform>> VERSION=$CIRCLE_TAG BRANCH=$CIRCLE_BRANCH OFFICIAL=0 SHOW=1 VERBOSE=1
      - persist-artifacts

  vm-platforms-build-steps:
    parameters:
      platform:
        type: string
    steps:
      - abort_for_docs
      - checkout-all
      - setup-automation
      - run:
          name: Install Docker
          command: bash <(curl -fsSL https://get.docker.com)
      - run:
          name: Build for platform
          command: |
            cd build/docker
            make build OSNICK=<<parameters.platform>> VERSION=$CIRCLE_TAG BRANCH=$CIRCLE_BRANCH ARTIFACTS=1 TEST=1 SHOW=1
          no_output_timeout: 30m
      - early_return_for_forked_pull_requests
      - run:
          name: Build for platform (publish)
          command: |
            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            cd build/docker
            make publish OSNICK=<<parameters.platform>> VERSION=$CIRCLE_TAG BRANCH=$CIRCLE_BRANCH OFFICIAL=0 SHOW=1 VERBOSE=1
      - persist-artifacts

#----------------------------------------------------------------------------------------------------------------------------------

jobs:
  valgrind:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - build_steps:
          platform: debian
          build_params: VALGRIND=1 -j
          test_params: VALGRIND=1 SIMPLE=1
          getredis_params: --valgrind

  lint:
    docker:
      - image: redislabsmodules/llvm-toolset:latest
    steps:
      - abort_for_docs
      - checkout-all
      - setup-automation
      - run:
          name: lint
          command: |
            make setup
            make lint

  build:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - build_steps:
          platform: debian

  platforms-build:
    parameters:
      platform:
        type: string
    docker:
      - image: debian:buster
    steps:
      - platforms-build-steps:
          platform: <<parameters.platform>>

  arm-platforms-build:
    parameters:
      platform:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - vm-platforms-build-steps:
          platform: <<parameters.platform>>

  build-macos:
    macos:
      xcode: 11.3.0
    steps:
      - run:
          name: Set up workspace
          command: |
            sudo mkdir -p ~/workspace
            sudo chown $USER ~/workspace
      - build_steps:
          platform: macos

  build-multiarch-docker:
    machine:
      enabled: true
      image: ubuntu-1604:202010-01
    steps:
      - abort_for_docs
      - checkout-all
      - run:
          name: Set up Python3
          command: pyenv global 3.7.0
      - run:
          name: Setup Docker client experimental features
          command: |
            sudo ./deps/readies/bin/getdocker --just-enable-exp
            docker version
      - run:
          name: Build
          command: |
            sudo docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            make -C build/docker build
            sudo make -C build/docker publish
          no_output_timeout: 20m

  coverage:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Pull Submodules
          command: git submodule update --init --recursive
      - run:
          name: Build & Test
          command: |
            make setup
            make build COV=1 SHOW=1
            make test COV=1
            bash <(curl -s https://codecov.io/bash) -f bin/linux-x64-debug-cov/cov.info
      - store_artifacts:
          path: coverage
          destination: coverage

  deploy-artifacts:
    parameters:
      location:
        type: string
        default: ""
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - attach_workspace:
          at: workspace
      - run:
          name: Deploy to S3
          command: |
            cd "workspace/artifacts/<<parameters.location>>"
            du -ah --apparent-size *
            if [[ -z <<parameters.location>> ]]; then
                path="/"
            else
                path="<<parameters.location>>/"
            fi
            for f in `ls *.zip *.tgz`; do
              aws s3 cp $f s3://redismodules/$PACKAGE_NAME/$path --acl public-read
            done

  release-automation:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - checkout
      - setup-automation
      - run:
          name: Run QA Automation
          command: MODULE_VERSION="$CIRCLE_TAG" VERBOSE=1 TEST=release ./tests/qa/run

  nightly-automation:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - checkout
      - setup-automation
      - run:
          name: Run QA Automation
          command: MODULE_VERSION="$CIRCLE_BRANCH" VERBOSE=1 TEST=nightly QUICK=1 ./tests/qa/run

#----------------------------------------------------------------------------------------------------------------------------------

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/

on-integ-branch: &on-integ-branch
  filters:
    branches:
      only:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      ignore: /.*/

not-on-integ-branch: &not-on-integ-branch
  filters:
    branches:
      ignore:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      ignore: /.*/

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-integ-and-version-tags: &on-integ-and-version-tags
  filters:
    branches:
      only:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      only: /^v[0-9].*/

#----------------------------------------------------------------------------------------------------------------------------------

workflows:
  version: 2
  default-flow:
    jobs:
      - lint:
          <<: *on-any-branch
      - valgrind:
          #@@ <<: *on-any-branch
          <<: *never
      - build:
          <<: *on-any-branch
      - platforms-build:
          <<: *on-any-branch
          context: common
          matrix:
            parameters:
              platform: [focal, bionic, xenial, centos7, centos8]
      - arm-platforms-build:
          <<: *on-any-branch
          context: common
          matrix:
            parameters:
              platform: [focal, bionic]
      - build-multiarch-docker:
          <<: *never
      - coverage:
          context: common
          <<: *on-any-branch
      - deploy-artifacts:
          name: deploy_snapshot
          location: snapshots
          context: common
          <<: *on-integ-branch
          requires:
            - platforms-build
            - arm-platforms-build
      - deploy-artifacts:
          name: deploy_release
          context: common
          <<: *on-version-tags
          requires:
            - platforms-build
            - arm-platforms-build
      - release-automation:
          context: common
          requires:
            - deploy_release
          <<: *on-version-tags

  nightly:
    triggers:
      - schedule:
          cron: "20 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-macos
      - valgrind
      - nightly-automation:
          context: common
